### ISSUE TITLE
models

### ISSUE THREAD

**Issue by tea7470** [VascoLopes/AutoClassifier#2]
hello. could you please send the models.zip for me ,thakyou verymuch

**Comment by VascoLopes** [comment]
Hi @tea7470,

There is no such file as models.zip.
The models are obtained using the `import torchvision.models`, and `import pretrainedmodels`

**Comment by tea7470** [comment]
hello,
&nbsp;which model is in "path_models&nbsp; = "/dataset/models/""




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VascoLopes/AutoClassifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VascoLopes/AutoClassifier] models (#2)





 
Hi @tea7470,
 
There is no such file as models.zip.
 The models are obtained using the import torchvision.models, and import pretrainedmodels

**Comment by VascoLopes** [comment]
If you are talking about:
[this line in autosklearn.py](https://github.com/VascoLopes/AutoClassifier/blob/3df08c396d9e8b514c0f631874e5e6b41eed0283/autosklearn.py#L27), the files in this folder are generated by running the `main.py.` In the last line of `main.py`, it stores the models that were evaluated. You can then use them for generating the new head using the `autosklearn.py`.
